void telaAddValor(void);
void addValorString(void);
void addValorInt(void);
void addValorFloat(void);
void telaConfirmacao(void);
int validarCNPJ(char []);
int verificarDigitosCNPJ(char cnpj[]);
int testarPrimeiroDigitoCNPJSubmetido(char []);
int testarSegundoDigitoCNPJSubmetido(char []);
int testarPrimeiroDigitoCPFSubmetido(char[]);
int testarSegundoDigitoCPFSubmetido(char[]);
int validarCPF(char[]);
