void telaAddValor(void);
void addValorString(void);
void addValorInt(void);
void addValorFloat(void);
void telaConfirmacao(void);
int validarCNPJ(char []);
int verificarDigitosCNPJ(char cnpj[]);
int testarPrimeiroDigitoCNPJSubmetido(char []);
int testarSegundoDigitoCNPJSubmetido(char []);
int testarPrimeiroDigitoSubmetido(char[11]);
int testarSegundoDigitoSubmetido(char[11]);
int validarCPF(char[11]);
