void telaAddValor(void);
void addValorString(void);
void addValorInt(void);
void addValorFloat(void);
void telaConfirmacao(void);
int validarCNPJ(char [14]);
int validarPrimeiroDigitoSubmetido(char [14]);
int validarSegundoDigitoSubmetido(char [14]);
int testarPrimeiroDigitoSubmetido(char[11]);
int testarSegundoDigitoSubmetido(char[11]);
int validarCPF(char[11]);
int validaData(char[11]);
int bissexto(int);
