char menuProduto(void);
void CadastroProduto(void);
void PesquisarProduto(void);
void ApagarProduto(void);
char AtualizarProduto(void);
void navegacaoMenuProduto(void);
void tratarData(void);
void tratarValidacaoNumeros(void);
void tratarValidacaoNome(void);
