char menuProduto(void);
void telaCadastroProduto(void);
void telaPesquisarProduto(void);
void telaApagarProduto(void);
char telaAtualizarProduto(void);
void navegacaoMenuProduto(void);
void tratarData(void);
void tratarValidacaoCodigo(void);
void tratarValidacaoNome(void);
