void navegacaoMenuRetirada(void);
char menuRetirada(void);
void telaCadastroRetirada(void);
void telaPesquisarRetirada(void);
void telaApagarRetirada(void);
void telaCodigoRetirada(void);
char telaAtualizarRetirada(void);
void tratarValidacaoCodigoRetirada(void);
void tratarValidacaoProdutoRetirada(void);
