char* telaAddValor(void);
int addValorInt(void);
float addValorFloat(void);
void telaConfirmacao(void);
int validarCodRetirada(char []);
int validarCNPJ(char []);
int testarPrimeiroDigitoCNPJSubmetido(char []);
int testarSegundoDigitoCNPJSubmetido(char []);
int testarPrimeiroDigitoCPFSubmetido(char[]);
int testarSegundoDigitoCPFSubmetido(char[]);
int validarCPF(char[]);
int verificarDigitos(char []);
int validaData(char[11]);
int bissexto(int);
int ehLetra(char);
int validacaoString(char *);
int validarCNPJ_CPF(char *);
void limparTela(void);
char* input(void);
char* alocarMemoria(int);
