void telaAddValor(void);
void addValorString(void);
void addValorInt(void);
void addValorFloat(void);
void telaConfirmacao(void);
int validarCNPJ(char []);
int testarPrimeiroDigitoCNPJSubmetido(char []);
int testarSegundoDigitoCNPJSubmetido(char []);
int testarPrimeiroDigitoCPFSubmetido(char[]);
int testarSegundoDigitoCPFSubmetido(char[]);
int validarCPF(char[]);
int verificarDigitos(char [],int);
int validaData(char[11]);
int bissexto(int);
